remote_theme: just-the-docs/just-the-docs@main
plugins:
- jekyll-remote-theme

title: Pasta Shape Recognizer
description: An image classification API that classifies 15 different types of pasta shapes

author:
  name: Zibran Zarif Amio