remote_theme: daattali/beautiful-jekyll
plugins:
- jekyll-remote-theme

title: Pasta Shape Recognizer
description: An image classification API that classifies 15 different types of pasta shapes

author:
  name: Zibran Zarif Amio