remote_theme: sylhare/Type-on-Strap
plugins:
- jekyll-remote-theme

title: Pasta Shape Recognizer
description: An image recognizer that recognizes 20 different shapes of Pasta.

author:
  name: Zibran Zarif Amio